version: "3"

services:
    app:
        build: .
        entrypoint: .docker/entrypoint.sh
        container_name: nodeApi
        ports:
            - "5000:5000"
        volumes:
            - .:/home/node/app
        depends_on:
            - db

    db:
        build: ./.docker/MongoDB
        container_name: MongoDB
        restart: always
        env_file: .env
        tty: true
        ports:
            - '27017:27017'
        volumes:
            - '/my/own/datadir:/data/db'
